---
- file:
    path: "{{ splunk_home }}/etc/apps/cluster_indexer_base/local/"
    state: directory
    mode: 0700

- file:
    path: "{{ splunk_home }}/etc/apps/cluster_indexer_base/metadata/"
    state: directory
    mode: 0700

- copy:
    src: /home/ec2-user/ansible-splunk/roles/cluster-peers/files/cp-server.conf
    dest: "{{ splunk_home }}/etc/apps/cluster_indexer_base/local/server.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: /home/ec2-user/ansible-splunk/roles/common/files/base-app.conf
    dest: "{{ splunk_home }}/etc/apps/cluster_indexer_base/local/app.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: /home/ec2-user/ansible-splunk/roles/common/files/base-local.meta
    dest: "{{ splunk_home }}/etc/apps/cluster_indexer_base/metadata/local.data"
    owner: splunk
    group: splunk
    mode: 0600
