---
- name: Changing Splunk default admin password 
  become: yes
  become_user: splunk
  shell: "{{ splunk_home }}/bin/splunk edit user admin -password {{ splunk_passwd }} -auth admin:changeme"
- name: Setting default password changed flag
  file:
    path: "{{ splunk_home }}/etc/.ui_login"
    owner: splunk
    group: splunk
    state: touch
    mode: 0644
- name: Restarted Splunk service
  service:
    name: splunk
    state: restarted
