---

- name: ensure collectd is installed
  yum:
    name: collectd
    state: present

- yum:
    name: collectd-write_http.x86_64
    state: present
    ignore_errors: yes

- name: configure collectd
  copy:
    src: "{{ playbook_home }}/roles/common/files/collectd.conf"
    dest: "/etc/collectd.d/splunk.conf"
    mode: 0600

- command: cat /etc/collectd.conf
  register: collectd

- name: Uncomment line from collectd.conf
  lineinfile:
    path: /etc/collectd.conf
    regexp: '^#Interval\s*10'
    line: 'Interval     1 '
    state: present
  when: collectd.stdout.find('Interval     1 ') == -1

- name: Start collectd service
  service:
    name: collectd
    state: restarted

- name: Enable collectd boot-statt
  service:
    name: collectd
    enabled: yes
