---
- file:
    path: "{{ splunk_home }}/etc/apps/cluster_master_base/local/"
    state: directory
    mode: 0700

- file:
    path: "{{ splunk_home }}/etc/apps/cluster_master_base/metadata/"
    state: directory
    mode: 0700

- template:
    src: "{{ playbook_home }}//roles/cluster-master/templates/cm-server.conf.j2"
    dest: "{{ splunk_home }}/etc/apps/cluster_master_base/local/server.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: "{{ playbook_home }}/roles/common/files/base-app.conf"
    dest: "{{ splunk_home }}/etc/apps/cluster_master_base/local/app.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: "{{ playbook_home }}/roles/common/files/base-local.meta"
    dest: "{{ splunk_home }}/etc/apps/cluster_master_base/metadata/local.data"
    owner: splunk
    group: splunk
    mode: 0600
