---
- name: Create license app in "{{ app_loc }}"
  file:
    path: "{{ splunk_home }}/etc/{{ app_loc }}/{{ app_license_all }}/local/"
    state: directory
    mode: 0700

- file:
    path: "{{ splunk_home }}/etc/{{ app_loc }}/{{ app_license_all }}/metadata/"
    state: directory
    mode: 0700

- template:
    src: "{{ playbook_home }}/roles/conf-manager/templates/server.conf.j2"
    dest: "{{ splunk_home }}/etc/{{ app_loc }}/{{ app_license_all }}/local/server.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: "{{ playbook_home }}/roles/common/files/base-app.conf"
    dest: "{{ splunk_home }}/etc/{{ app_loc }}/{{ app_license_all }}/local/app.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: "{{ playbook_home }}/roles/common/files/base-local.meta"
    dest: "{{ splunk_home }}/etc/{{ app_loc }}/{{ app_license_all }}/metadata/local.data"
    owner: splunk
    group: splunk
    mode: 0600

