---
- file:
    path: "{{ splunk_home }}/etc/apps/{{ app_cluster_passkey }}/local/"
    state: directory
    mode: 0700

- file:
    path: "{{ splunk_home }}/etc/apps/{{ app_cluster_passkey }}/metadata/"
    state: directory
    mode: 0700

- template:
    src: "{{ playbook_home }}/roles/cluster-all/templates/pk-server.conf.j2"
    dest: "{{ splunk_home }}/etc/apps/{{ app_cluster_passkey }}/local/server.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: "{{ playbook_home }}/roles/common/files/base-app.conf"
    dest: "{{ splunk_home }}/etc/apps/{{ app_cluster_passkey }}/local/app.conf"
    owner: splunk
    group: splunk
    mode: 0600

- copy:
    src: "{{ playbook_home }}/roles/common/files/base-local.meta"
    dest: "{{ splunk_home }}/etc/apps/{{ app_cluster_passkey }}/metadata/local.data"
    owner: splunk
    group: splunk
    mode: 0600
